spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

app:
  rabbitmq:
    exchange: hotel-exchange
    queues:
      rating: rating-queue
      hotel: hotel-embedding-queue
    routing:
      ratingEmbedding: hotel.rating
      hotelEmbedding: hotel.embedding

logging:
  level:
    org.springframework: INFO
    com.kapoor: DEBUG

  file:
    name: logs/spring-boot-application.log

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
